### PR TITLE
Extend appdata.xml and align with AppStream specification

### PR DESCRIPTION
**Pull request by dhet**
This change is to extend the appdata.xml file and align it with the [AppStream spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html)
* Add [launchable tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable)
* The description tag [only supports a small subset of HTML](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description). For this I added a utility script which extracts a description from the cryptomator readme. Please note that the description generation is not (yet) automated
* Add some [categories](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-categories)
* The [.desktop file should be named like the application ID](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-contents)

### CODE REVIEW

**Comment by overheadhunter** [comment]
Looks good so far. While we're discussing this: Shouldn't the file be named according to its ID? I.e. since we're saying `<id>org.cryptomator.cryptomator</id>`, it should be `org.cryptomator.cryptoamtor.appdata.xml`, right?

Will this PR close issue #4 as well?

**Comment by overheadhunter** [comment]
Also, to [quote the spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic), id should better be `org.cryptomator.Cryptomator`:

> The ID must follow a reverse-DNS scheme, consisting of {tld}.{vendor}.{product}, for example org.kde.Gwenview or com.hugski.ColorHug2.

(note the camelcased product name)

**Comment by dhet** [comment]
Yes, you're right. I fixed the naming in d525325.
This should solve the issue. Also, we should inform the last commenter that the app ID has changed.

**Comment by overheadhunter** [comment]
Thank you! ❤️

**Pull request merged**
